# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Audience
    url: /#who
    weight: 20
  - name: Schedule
    url: /#schedule
    weight: 30
  - name: Events
    url: /#event
    weight: 40
  - name: Participate
    url: /#participate
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
  - name: Detail information
    url: docs/
    weight: 70
