# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the file- name of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# main:
#   - - name: Home
#     url: /
#     weight: 10
#   - - name: About
#     url: /#about
#     weight: 20
#   - - name: Audience
#     url: /#who
#     weight: 20
#   - - name: Events
#     url: /#event
#     weight: 30
#   - - name: Schedule
#     url: /#schedule
#     weight: 40
#   - - name: Participate
#     url: /#participate
#     weight: 50
#   - - name: Contact
#     url: /#contact
#     weight: 60
#   - - name: More information
#     url: docs/
#     weight: 70

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the file- name of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: "Home"
    url: "https://escalator.sadilar.org/"
    weight: 10

  - name: "Resources"
    weight: 40

  - name: "DH-IGNITE KZN"
    url: "past_events/kzn/"
    weight: 10
    parent: "Resources"

  - name: "DH-IGNITE WC"
    url: "past_events/wc/"
    weight: 20
    parent: "Resources"
  
  - name: "DH-IGNITE C&WR"
    url: "past_events/cwr/"
    weight: 30
    parent: "Resources"

  - name: "Contact"
    url: "#contact"
    weight: 60

  - name: "Blog"
    url: "post"
    weight: 70

  




