# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the file- name of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# main:
#   - - name: Home
#     url: /
#     weight: 10
#   - - name: About
#     url: /#about
#     weight: 20
#   - - name: Audience
#     url: /#who
#     weight: 20
#   - - name: Events
#     url: /#event
#     weight: 30
#   - - name: Schedule
#     url: /#schedule
#     weight: 40
#   - - name: Participate
#     url: /#participate
#     weight: 50
#   - - name: Contact
#     url: /#contact
#     weight: 60
#   - - name: More information
#     url: docs/
#     weight: 70

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the file- name of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: "Home"
    url: "/"
    weight: 10

  - name: "About"
    url: "#about"
    weight: 20

  - name: "About DH-IGNITE"
    url: "#about"
    weight: 10
    parent: "About"

  - name: "Audience"
    url: "#who"
    weight: 30
    parent: "About"

  - name: "Upcoming events"
    url: "#event"
    weight: 40
    parent: "About"

  - name: "Resources"
    weight: 40

  - name: "DH-IGNITE KZN"
    url: "resources/kzn/"
    weight: 10
    parent: "Resources"

  - name: "DH-IGNITE WC"
    url: "resources/wc/"
    weight: 20
    parent: "Resources"
  
  - name: "DH-IGNITE C&WR"
    url: "resources/cwr/"
    weight: 30
    parent: "Resources"


  # - name: "Speakers"
  #   url: "#speakers"
  #   weight: 40

  # - name: "Workshops"
  #   url: "#workshops"
  #   weight: 50

  - name: "Contact"
    url: "#contact"
    weight: 60

  - name: "Blog"
    url: "post"
    weight: 70

  - name: "Important information"
    weight: 80

  - name: "General information"
    url: "docs/"
    weight: 10
    parent: "Important information"
  




